name: flutter_hello_world
description: 一個新的 Flutter 專案。

# 如果你想要發佈到 pub.dev，移除這行
publish_to: 'none'

# 版本號 (依照 Semantic Versioning 規範)
version: 0.0.1+1

environment:
  # 設定 Dart SDK 版本範圍，支援 3.1.1 到 4.0.0 之前的版本
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 引入 english_words 套件，通常用於隨機英文單字生成
  english_words: ^4.0.0

  # 引入 provider 套件，用於狀態管理
  provider: ^6.0.0

  # 如果應用程序使用 Cupertino (iOS 樣式設計)，可以加入這個套件
  # cupertino_icons: ^1.0.0

  # 如果你的應用程序需要本地化支援（多語言），可以引入 intl 套件
  # intl: ^0.18.0

dev_dependencies:
  # Flutter 預設的測試框架
  flutter_test:
    sdk: flutter

  # Flutter 預設的 lint 規則，用來保持代碼風格一致
  flutter_lints: ^2.0.0

  # 引入 mockito，用於單元測試中的模擬物件
  # mockito: ^5.3.0

  # 引入 very_good_analysis 套件，提供更嚴格的靜態分析
  # very_good_analysis: ^4.0.0

flutter:
  # 啟用 Material Design 圖標
  uses-material-design: true
